language: php
php:
- '7.0'
- '7.1'
- '7.2'
- nightly
matrix:
  fast_finish: true
  allow_failures:
  - php: '7.2'
  - php: nightly
before_install:
- phpenv config-rm xdebug.ini || true
- composer config --global github-oauth.github.com $GITHUB_TOKEN
install: composer install --no-interaction
script: make ci -j 50
cache:
  directories:
  - $HOME/.composer
